user.pool.id: us-east-1_2HfXbVOoy

spring:
  security:
    oauth2:
      client:
        registration:
          cognito:
            clientId: 5m5m87p2chmsf8rq8lj0q3d5e
            scope: openid
        provider:
          cognito:
            issuerUri: https://cognito-idp.us-east-1.amazonaws.com/${user.pool.id}

  flyway:
    enabled: false

  datasource:
    url: jdbc:mysql://localhost:3306/pizza_system?useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: 123456
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: none
  mail:
    host: localhost
    port: 1025
